import {readFileSync,writeFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as w from '../src/wad/index';
const bytes=readFileSync(process.env.DOOM_WAD ?? 'public/doomu.wad');
const wad=w.parseWAD(bytes.buffer.slice(bytes.byteOffset,bytes.byteOffset+bytes.byteLength));
const lines=new Map<number,{count:number;maps:Set<string>}>(),sectors=new Map<number,{count:number;maps:Set<string>}>();
for(const marker of wad.lumps.filter(l=>/^E[1-4]M[1-9]$/.test(l.name))) {
  const map=w.getMapLumps(wad,marker.name);
  for(const [items,table] of [[w.parseLinedefs(wad,map.LINEDEFS),lines],[w.parseSectors(wad,map.SECTORS),sectors]] as const) {
    for(const item of items) {
      if(!item.special)continue;
      const row=table.get(item.special) ?? {count:0,maps:new Set<string>()};
      row.count++;row.maps.add(marker.name);table.set(item.special,row);
    }
  }
}
const table=(rows:typeof lines)=>[...rows].sort(([a],[b])=>a-b).map(([n,row])=>`| ${n} | ${row.count} | ${[...row.maps].join(', ')} |`).join('\n');
const report=`# Supplied IWAD special inventory\n\nGenerated by \`npm run inventory:specials\`. SHA-256: \`${createHash('sha256').update(bytes).digest('hex')}\`. Counts are coverage input, not evidence of correct implementation. Every used special needs dispatch, behavior, and a scenario.\n\n## Linedefs\n\n| Special | Count | Maps |\n|---|---|---|\n${table(lines)}\n\n## Sectors\n\n| Special | Count | Maps |\n|---|---|---|\n${table(sectors)}\n`;
writeFileSync('docs/IWAD-SPECIALS.md',report);
console.log(`Inventoried ${lines.size} line and ${sectors.size} sector specials.`);
